blank_issues_enabled: false
contact_links:
  - name: "SPSSiteInventory Discussions"
    url: https://github.com/luigilink/SPSSiteInventory/discussions
    about: "To engage with the community and maintainers of SPSSiteInventory, please visit the discussions group. There, you can share feedback, ask questions, and collaborate with others working on SPSSiteInventory."
